# Generated by Django 5.2 on 2025-05-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_produto_estoque_alter_produto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='est',
            field=models.IntegerField(default=0, verbose_name=132),
            preserve_default=False,
        ),
    ]
