# Generated by Django 5.2 on 2025-05-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_produto_est'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='est',
            field=models.IntegerField(default=32),
        ),
    ]
